#Configuration File
mongo:
  use: false
  hostname: localhost
  port: 27017
  database: chat
  username: chat
  password: chat
file:
  save_pretty: false
region:
  visitor: 'visitor'
  visitor_world: 'world'
  spawn: 'spawn'
  spawn_world: 'world'
targeting:
  max_range: 100
time_multiplier:
  daylight: 2
  night: 1
  worlds: [world]
